---
# file: foundation-ubuntu.yml

- hosts: 127.0.0.1
  connection: local
  become: yes
  pre_tasks:
  - name: ensure Java 8 repo is installed
    apt_repository:
      repo: ppa:openjdk-r/ppa
  - name: ensure brightbox repository is present for ruby installs
    apt_repository:
      repo: ppa:brightbox/ruby-ng
      state: present
      update_cache: yes
  - name: ensure necessary system dependencies are installed
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - git
      - jq
      - ntp
      - ruby2.3
      - ruby2.3-dev
      - zlib1g-dev
  - name: ensure deb-s3 is installed
    gem:
      name: deb-s3
      state: latest
  - name: Fetch Jenkins 1.658 # https://github.com/geerlingguy/ansible-role-jenkins/issues/47
    get_url:
      url: http://pkg.jenkins-ci.org/debian/binary/jenkins_1.658_all.deb
      dest: /tmp/jenkins_1.658_all.deb
  - name: Install Jenkins 1.658
    apt:
      deb: /tmp/jenkins_1.658_all.deb
  - name: ensure ca stores for java are updated
    command: update-ca-certificates -f
  roles:
  - role: cloud-init
  - role: cloudwatch
    cloudwatch_region: us-east-1
    logs:
    - file: /var/log/syslog
      format: "%b %d %H:%M:%S"
      group_name: jenkins
      stream_name: "{instance_id}-syslog"
    - file: /var/log/kern.log
      format: "%b %d %H:%M:%S"
      group_name: jenkins
      stream_name: "{instance_id}-kern.log"
    - file: /var/log/jenkins/jenkins.log
      format: "%b %d %Y %I:%M:%S %p"
      group_name: jenkins
      stream_name: "{instance_id}-jenkins.log"
  - role: geerlingguy.java
    when: "ansible_os_family == 'Debian'"
    java_packages:
    - openjdk-8-jdk
  - role: geerlingguy.jenkins
    jenkins_plugins:
    - credentials-binding
    - envinject
    - git
    - git-parameter
    - github-api
    - github
    - job-dsl
    - jobConfigHistory
    - kubernetes
    - parameterized-trigger
    - shelve-project-plugin
    - slack
    - ssh
    - swarm
    - ws-cleanup
    - plain-credentials
    - postbuildscript
    - s3
  - role: geerlingguy.haproxy
    haproxy_backend_servers:
    - name: jenkins
      address: 127.0.0.1:8080